version: "3.8"
services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=Panel
      - POSTGRES_PASSWORD=testPassword # will not be used in prod
      - POSTGRES_DB=PanelDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
